export const countries = [
    { name: "Afganistán", code: "AF", codeCountry: "+93" },
    { name: "Albania", code: "AL", codeCountry: "+355" },
    { name: "Argelia", code: "DZ", codeCountry: "+213" },
    { name: "Andorra", code: "AD", codeCountry: "+376" },
    { name: "Angola", code: "AO", codeCountry: "+244" },
    { name: "Argentina", code: "AR", codeCountry: "+54" },
    { name: "Armenia", code: "AM", codeCountry: "+374" },
    { name: "Australia", code: "AU", codeCountry: "+61" },
    { name: "Austria", code: "AT", codeCountry: "+43" },
    { name: "Azerbaiyán", code: "AZ", codeCountry: "+994" },
    { name: "Bahamas", code: "BS", codeCountry: "+1-242" },
    { name: "Baréin", code: "BH", codeCountry: "+973" },
    { name: "Bangladés", code: "BD", codeCountry: "+880" },
    { name: "Bielorrusia", code: "BY", codeCountry: "+375" },
    { name: "Bélgica", code: "BE", codeCountry: "+32" },
    { name: "Belice", code: "BZ", codeCountry: "+501" },
    { name: "Benín", code: "BJ", codeCountry: "+229" },
    { name: "Bután", code: "BT", codeCountry: "+975" },
    { name: "Bolivia", code: "BO", codeCountry: "+591" },
    { name: "Bosnia y Herzegovina", code: "BA", codeCountry: "+387" },
    { name: "Botsuana", code: "BW", codeCountry: "+267" },
    { name: "Brasil", code: "BR", codeCountry: "+55" },
    { name: "Brunéi", code: "BN", codeCountry: "+673" },
    { name: "Bulgaria", code: "BG", codeCountry: "+359" },
    { name: "Burkina Faso", code: "BF", codeCountry: "+226" },
    { name: "Burundi", code: "BI", codeCountry: "+257" },
    { name: "Cabo Verde", code: "CV", codeCountry: "+238" },
    { name: "Camboya", code: "KH", codeCountry: "+855" },
    { name: "Camerún", code: "CM", codeCountry: "+237" },
    { name: "Canadá", code: "CA", codeCountry: "+1" },
    { name: "República Centroafricana", code: "CF", codeCountry: "+236" },
    { name: "Chad", code: "TD", codeCountry: "+235" },
    { name: "Chile", code: "CL", codeCountry: "+56" },
    { name: "China", code: "CN", codeCountry: "+86" },
    { name: "Colombia", code: "CO", codeCountry: "+57" },
    { name: "Comoras", code: "KM", codeCountry: "+269" },
    { name: "Congo", code: "CG", codeCountry: "+242" },
    { name: "Costa Rica", code: "CR", codeCountry: "+506" },
    { name: "Croacia", code: "HR", codeCountry: "+385" },
    { name: "Cuba", code: "CU", codeCountry: "+53" },
    { name: "Chipre", code: "CY", codeCountry: "+357" },
    { name: "Chequia", code: "CZ", codeCountry: "+420" },
    { name: "Dinamarca", code: "DK", codeCountry: "+45" },
    { name: "Yibuti", code: "DJ", codeCountry: "+253" },
    { name: "Dominica", code: "DM", codeCountry: "+1-767" },
    { name: "República Dominicana", code: "DO", codeCountry: "+1-809" },
    { name: "Ecuador", code: "EC", codeCountry: "+593" },
    { name: "Egipto", code: "EG", codeCountry: "+20" },
    { name: "El Salvador", code: "SV", codeCountry: "+503" },
    { name: "Estonia", code: "EE", codeCountry: "+372" },
    { name: "Esuatini", code: "SZ", codeCountry: "+268" },
    { name: "Etiopía", code: "ET", codeCountry: "+251" },
    { name: "Fiyi", code: "FJ", codeCountry: "+679" },
    { name: "Finlandia", code: "FI", codeCountry: "+358" },
    { name: "Francia", code: "FR", codeCountry: "+33" },
    { name: "Gabón", code: "GA", codeCountry: "+241" },
    { name: "Gambia", code: "GM", codeCountry: "+220" },
    { name: "Georgia", code: "GE", codeCountry: "+995" },
    { name: "Alemania", code: "DE", codeCountry: "+49" },
    { name: "Ghana", code: "GH", codeCountry: "+233" },
    { name: "Grecia", code: "GR", codeCountry: "+30" },
    { name: "Granada", code: "GD", codeCountry: "+1-473" },
    { name: "Guatemala", code: "GT", codeCountry: "+502" },
    { name: "Guinea", code: "GN", codeCountry: "+224" },
    { name: "Guinea-Bisáu", code: "GW", codeCountry: "+245" },
    { name: "Guyana", code: "GY", codeCountry: "+592" },
    { name: "Haití", code: "HT", codeCountry: "+509" },
    { name: "Honduras", code: "HN", codeCountry: "+504" },
    { name: "Hungría", code: "HU", codeCountry: "+36" },
    { name: "Islandia", code: "IS", codeCountry: "+354" },
    { name: "India", code: "IN", codeCountry: "+91" },
    { name: "Indonesia", code: "ID", codeCountry: "+62" },
    { name: "Irán", code: "IR", codeCountry: "+98" },
    { name: "Irak", code: "IQ", codeCountry: "+964" },
    { name: "Irlanda", code: "IE", codeCountry: "+353" },
    { name: "Israel", code: "IL", codeCountry: "+972" },
    { name: "Italia", code: "IT", codeCountry: "+39" },
    { name: "Jamaica", code: "JM", codeCountry: "+1-876" },
    { name: "Japón", code: "JP", codeCountry: "+81" },
    { name: "Jordania", code: "JO", codeCountry: "+962" },
    { name: "Kazajistán", code: "KZ", codeCountry: "+7" },
    { name: "Kenia", code: "KE", codeCountry: "+254" },
    { name: "Kuwait", code: "KW", codeCountry: "+965" },
    { name: "Kirguistán", code: "KG", codeCountry: "+996" },
    { name: "Laos", code: "LA", codeCountry: "+856" },
    { name: "Letonia", code: "LV", codeCountry: "+371" },
    { name: "Líbano", code: "LB", codeCountry: "+961" },
    { name: "Lesoto", code: "LS", codeCountry: "+266" },
    { name: "Liberia", code: "LR", codeCountry: "+231" },
    { name: "Libia", code: "LY", codeCountry: "+218" },
    { name: "Lituania", code: "LT", codeCountry: "+370" },
    { name: "Luxemburgo", code: "LU", codeCountry: "+352" },
    { name: "Madagascar", code: "MG", codeCountry: "+261" },
    { name: "Malaui", code: "MW", codeCountry: "+265" },
    { name: "Malasia", code: "MY", codeCountry: "+60" },
    { name: "Maldivas", code: "MV", codeCountry: "+960" },
    { name: "Malí", code: "ML", codeCountry: "+223" },
    { name: "Malta", code: "MT", codeCountry: "+356" },
    { name: "Mauritania", code: "MR", codeCountry: "+222" },
    { name: "Mauricio", code: "MU", codeCountry: "+230" },
    { name: "México", code: "MX", codeCountry: "+52" },
    { name: "Moldavia", code: "MD", codeCountry: "+373" },
    { name: "Mónaco", code: "MC", codeCountry: "+377" },
    { name: "Mongolia", code: "MN", codeCountry: "+976" },
    { name: "Montenegro", code: "ME", codeCountry: "+382" },
    { name: "Marruecos", code: "MA", codeCountry: "+212" },
    { name: "Mozambique", code: "MZ", codeCountry: "+258" },
    { name: "Birmania", code: "MM", codeCountry: "+95" },
    { name: "Namibia", code: "NA", codeCountry: "+264" },
    { name: "Nepal", code: "NP", codeCountry: "+977" },
    { name: "Países Bajos", code: "NL", codeCountry: "+31" },
    { name: "Nueva Zelanda", code: "NZ", codeCountry: "+64" },
    { name: "Nicaragua", code: "NI", codeCountry: "+505" },
    { name: "Níger", code: "NE", codeCountry: "+227" },
    { name: "Nigeria", code: "NG", codeCountry: "+234" },
    { name: "Corea del Norte", code: "KP", codeCountry: "+850" },
    { name: "Macedonia del Norte", code: "MK", codeCountry: "+389" },
    { name: "Noruega", code: "NO", codeCountry: "+47" },
    { name: "Omán", code: "OM", codeCountry: "+968" },
    { name: "Pakistán", code: "PK", codeCountry: "+92" },
    { name: "Palestina", code: "PS", codeCountry: "+970" },
    { name: "Panamá", code: "PA", codeCountry: "+507" },
    { name: "Papúa Nueva Guinea", code: "PG", codeCountry: "+675" },
    { name: "Paraguay", code: "PY", codeCountry: "+595" },
    { name: "Perú", code: "PE", codeCountry: "+51" },
    { name: "Filipinas", code: "PH", codeCountry: "+63" },
    { name: "Polonia", code: "PL", codeCountry: "+48" },
    { name: "Portugal", code: "PT", codeCountry: "+351" },
    { name: "Catar", code: "QA", codeCountry: "+974" },
    { name: "Rumania", code: "RO", codeCountry: "+40" },
    { name: "Rusia", code: "RU", codeCountry: "+7" },
    { name: "Ruanda", code: "RW", codeCountry: "+250" },
    { name: "Arabia Saudita", code: "SA", codeCountry: "+966" },
    { name: "Senegal", code: "SN", codeCountry: "+221" },
    { name: "Serbia", code: "RS", codeCountry: "+381" },
    { name: "Singapur", code: "SG", codeCountry: "+65" },
    { name: "Eslovaquia", code: "SK", codeCountry: "+421" },
    { name: "Eslovenia", code: "SI", codeCountry: "+386" },
    { name: "Somalia", code: "SO", codeCountry: "+252" },
    { name: "Sudáfrica", code: "ZA", codeCountry: "+27" },
    { name: "Corea del Sur", code: "KR", codeCountry: "+82" },
    { name: "Sudán del Sur", code: "SS", codeCountry: "+211" },
    { name: "España", code: "ES", codeCountry: "+34" },
    { name: "Sri Lanka", code: "LK", codeCountry: "+94" },
    { name: "Sudán", code: "SD", codeCountry: "+249" },
    { name: "Surinam", code: "SR", codeCountry: "+597" },
    { name: "Suecia", code: "SE", codeCountry: "+46" },
    { name: "Suiza", code: "CH", codeCountry: "+41" },
    { name: "Siria", code: "SY", codeCountry: "+963" },
    { name: "Taiwán", code: "TW", codeCountry: "+886" },
    { name: "Tayikistán", code: "TJ", codeCountry: "+992" },
    { name: "Tanzania", code: "TZ", codeCountry: "+255" },
    { name: "Tailandia", code: "TH", codeCountry: "+66" },
    { name: "Togo", code: "TG", codeCountry: "+228" },
    { name: "Trinidad y Tobago", code: "TT", codeCountry: "+1-868" },
    { name: "Túnez", code: "TN", codeCountry: "+216" },
    { name: "Turquía", code: "TR", codeCountry: "+90" },
    { name: "Turkmenistán", code: "TM", codeCountry: "+993" },
    { name: "Uganda", code: "UG", codeCountry: "+256" },
    { name: "Ucrania", code: "UA", codeCountry: "+380" },
    { name: "Emiratos Árabes Unidos", code: "AE", codeCountry: "+971" },
    { name: "Reino Unido", code: "GB", codeCountry: "+44" },
    { name: "Estados Unidos", code: "US", codeCountry: "+1" },
    { name: "Uruguay", code: "UY", codeCountry: "+598" },
    { name: "Uzbekistán", code: "UZ", codeCountry: "+998" },
    { name: "Vanuatu", code: "VU", codeCountry: "+678" },
    { name: "Venezuela", code: "VE", codeCountry: "+58" },
    { name: "Vietnam", code: "VN", codeCountry: "+84" },
    { name: "Yemen", code: "YE", codeCountry: "+967" },
    { name: "Zambia", code: "ZM", codeCountry: "+260" },
    { name: "Zimbabue", code: "ZW", codeCountry: "+263" }
]